name: lms-rust
on:
  pull_request:
    paths:
      - ".github/workflows/lms-rust.yml"
      - "lms/**"
      - "Cargo.*"
  push:
    branches: main

defaults:
  run:
    working-directory: .

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.73.0 # MSRV for RustCrypto
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - run: cargo clippy --no-default-features
      - run: cargo clippy
      - run: cargo clippy --all-features

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.73.0 # MSRV for RustCrypto
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo check --all-features
      - run: cargo test --no-default-features
      - run: cargo test
      - run: cargo test --all-features
