name: ecdsa
on:
  pull_request:
    paths:
      - ".github/workflows/ecdsa.yml"
      - "ecdsa/**"
      - "rfc6979/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: ecdsa

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  no_std:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
        rust:
          - 1.73.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - uses: RustCrypto/actions/cargo-hack-install@master
      - run: cargo hack build --target ${{ matrix.target }} --feature-powerset --exclude-features std

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.73.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo check --all-features
      - run: cargo test --no-default-features
      - run: cargo test
      - run: cargo test --all-features
