name: ed448
on:
  pull_request:
    paths:
      - "ed448/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: ed448

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
        toolchain:
          - 1.60.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          targets: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features --features alloc
      # TODO(tarcieri): re-enable the following when MSRV is 1.65
      #- run: cargo build --target ${{ matrix.target }} --release --no-default-features --features pem
      #- run: cargo build --target ${{ matrix.target }} --release --no-default-features --features pkcs8
      #- run: cargo build --target ${{ matrix.target }} --release --no-default-features --features alloc,pem,pkcs8

  test:
    strategy:
      matrix:
        toolchain:
          - 1.65.0 # Technically MSRV is 1.60, but we have 1.65 dev-dependencies (i.e. ring-compat)
          - stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test --release --no-default-features
      - run: cargo test --release
      - run: cargo test --release --all-features
