name: Security Audit
on:
  pull_request:
    paths: '**/Cargo.lock'
  push:
    branches: master
    paths: '**/Cargo.lock'
  schedule:
    - cron: "0 0 * * *"

jobs:
  security_audit_workspace:
    name: Security Audit Workspace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-audit-v0.15.2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  security_audit_ed25519:
    name: Security Audit ed25519
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ed25519
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-audit-v0.15.2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
